version: '3.7'

services:
  tanks_web_client:
    image: nginx:alpine
    volumes:
      - ./docker/webgl-client:/usr/share/nginx/html:ro
    # Uncomment below in case debugging is desired
    # ports:
      # - "8080:80"

  tanks_server:
    build:
      context: ./docker/dedicated-linux-server
    # TODO: how can I run docker-compose logs -f tanks_server and see the server.log at /root/server.log?
    # command:
      # - /usr/bin/tail
      # - -f
      # - /root/server.log
    # Uncomment below in case debugging is desired
    # ports:
      # - "7777:7777/udp"
      # - "7778:7778/tcp"

  proxy:
    image: nginx:alpine
    volumes:
      - ./docker/reverse-proxy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/reverse-proxy/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "7777:7777/udp"
      - "7778:7778/tcp"
    depends_on:
      - tanks_web_client
      - tanks_server
